name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          USERNAME: smnm1998
      - name: Commit & Push
        run: |
          git config user.name "smnm1998"
          git config user.email "dltpals7498@gmail.com"
          git add -A .
          git commit -m "generated"
          git push
